---

#
# Common tasks
#

- name: "Set fact: type of environment"
  set_fact:
    is_dev: "{{ old_src_environment_type == 'development' }}"
    is_prod: "{{ old_src_environment_type == 'production' }}"
  tags: "always" # inocuous to use always here

- include: "tear-up.yml"
  tags: # do not use "always" tag in role, to avoid issues when including other roles in a playbook
  - "oldsrc"

- name: "Ensure pip is not installed from packages"
  package:
    name: "{{ item }}"
    state: "absent"
  with_items:
    - "python-pip"
    - "python2-pip"
    - "python3-pip"

- name: "Download get-pip.py"
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: "/root/get-pip.py"

- name: "Install pip with get-pip.py"
  command: "python get-pip.py"
  args:
    chdir: "/root/"

- name: "Install virtualenv with pip"
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "virtualenv"


#
# Online Linguistic Database
#

- include: "old-main.yml"
  tags:
   - "oldsrc"
  when: "old_src_install|bool"
