---

#
# Common tasks
#

- name: "Set fact: type of environment"
  set_fact:
    is_dev: "{{ old_src_environment_type == 'development' }}"
    is_prod: "{{ old_src_environment_type == 'production' }}"
  tags: "always" # inocuous to use always here

- include: "tear-up.yml"
  tags: # do not use "always" tag in role, to avoid issues when including other roles in a playbook
  - "oldsrc"


#
# Online Linguistic Database
#

- include: "old-main.yml"
  tags:
   - "oldsrc"
  when: "old_src_install|bool"

- include: "old-db.yml"
  tags:
   - "oldsrc"
   - "oldsrc-db"
  when: "old_src_install|bool"

#- include: "websrv-uwsgi.yml"
#  tags:
#   - "oldsrc"
#  when: "old_src_install|bool and not(old_src_gunicorn|bool)"

#- include: "websrv-gunicorn.yml"
#  tags:
#   - "oldsrc"
#  when: "old_src_install|bool and old_src_gunicorn|bool"


#
# OLD install
#
#   1. OS dependencies (foma, MITLM, ffmpeg --- debian packages & source)
#   2. python dependencies (pip packages)
#   3. OS configuration (user/directory/file creation/permissions/ownership)
#   4. Code install
#   5. Database config
#   6. web server config

# Creates a bunch of directories.
#- include: "old-osconf.yml"
#  tags:
#    - "oldsrc"
#    - "oldsrc-osconf"
#  when: "old_src_install|bool"

#- include: "instcode.yml"
#  tags:
#    - "oldsrc"
#    - "oldsrc-instcode"
#  when: "old_src_install|bool"

