---

#
# Common tasks
#

- name: "Set fact: type of environment"
  set_fact:
    is_dev: "{{ old_src_environment_type == 'development' }}"
    is_prod: "{{ old_src_environment_type == 'production' }}"
  tags: "always" # inocuous to use always here

- include: "tear-up.yml"
  tags: # do not use "always" tag in role, to avoid issues when including other roles in a playbook
  - "oldsrc"


#
# Online Linguistic Database
#

- include: "old-main.yml"
  tags:
   - "oldsrc"
  when: "old_src_install|bool"
