---

# TODO: not sure if any of this is required for the OLD ...

###########################################################
#   3. OS configuration (user/directory/file creation/permissions/ownership )
###########################################################

- name: "Create subdirectories for archivematica-common source files"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/usr/lib/archivematica"
    - "/etc/archivematica/archivematicaCommon"
    - "/usr/share/archivematica/archivematicaCommon"

- name: "Create archivematica-dashboard log directories"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    mode: "g+s"
  with_items:
    - "/var/log/archivematica/dashboard"

- name: "Create subdirectories for archivematica-mcp-server source files"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/etc/archivematica/MCPServer"
    - "/usr/lib/archivematica"
    - "/usr/share/archivematica"
    - "/usr/share/dbconfig-common/data/archivematica-mcp-server/install/"
    - "/usr/share/dbconfig-common/data/archivematica-mcp-server/upgrade/mysql/"

- name: "Create archivematica-mcp-server log directories"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    mode: "g+s"
  with_items:
    - "/var/log/archivematica/MCPServer"

- name: "Clear /var/archivematica/sharedDirectory"
  file:
    dest: "/var/archivematica/sharedDirectory"
    state: "absent"
  when: "archivematica_src_reset_shareddir|bool or archivematica_src_reset_am_all|bool"

- name: "Create /var/archivematica/sharedDirectory"
  file:
    dest: "/var/archivematica/sharedDirectory"
    state: "directory"

- name: "Create /var/archivematica/sharedDirectory structure"
  command: "rsync -a {{ archivematica_src_dir }}/archivematica/src/MCPServer/share/sharedDirectoryStructure/ /var/archivematica/sharedDirectory/"

- name: "Set owner, group of /var/archivematica recursively"
  file:
    dest: "/var/archivematica"
    state: "directory"
    recurse: "yes"
    owner: "archivematica"
    group: "archivematica"

- name: "Set owner, group of /var/archivematica/sharedDirectory recursively"
  file:
    dest: "/var/archivematica/sharedDirectory"
    state: "directory"
    recurse: "yes"
    owner: "archivematica"
    group: "archivematica"

- name: "Set permissions for /var/archivematica"
  file:
    path: "/var/archivematica/"
    mode: "g+s"

- name: "Set permissions for /var/archivematica/sharedDirectory"
  file:
    path: "/var/archivematica/sharedDirectory"
    mode: 0664

- name: "Set more permissions for /var/archivematica"
  shell: "find -L /var/archivematica/ -print0 -type d  | sudo xargs -IF -0 chmod u+rwx,g+rwxt,o-rwx F"

- name: "Create subdirectories for archivematica-mcp-client source files"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/etc/archivematica/MCPClient"
    - "/usr/lib/archivematica"

- name: "Create archivematica-mcp-client log directories"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    mode: "g+s"
  with_items:
    - "/var/log/archivematica/MCPClient"
