---

# TODO: not sure if any of this is required for the OLD ...

###########################################################
#   4. Code install
###########################################################

- name: "Symlink archivematica-common source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/lib"
      dest: "/usr/lib/archivematica/archivematicaCommon"
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements.txt"
      dest: "/usr/share/archivematica/archivematicaCommon/requirements.txt"
    - src: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements"
      dest: "/usr/share/archivematica/archivematicaCommon/requirements"

- name: "Template archivematica-common /etc config"
  template:
    src: "etc_archivematica_archivematicaCommon_dbsettings.j2"
    dest: "/etc/archivematica/archivematicaCommon/dbsettings"
    backup: "yes"

- name: "Copy archivematica-dashboard source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/dashboard/src"
      dest: "/usr/share/archivematica/dashboard"


- name: "Copy archivematica-mcp-server source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/lib"
      dest: "/usr/lib/archivematica/MCPServer"
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPServer/share"
      dest: "/usr/share/archivematica/MCPServer"

- name: "template MCPServer /etc config"
  template:
    src: "etc_archivematica_MCPServer_serverConfig.conf.j2"
    dest: "/etc/archivematica/MCPServer/serverConfig.conf"
    backup: "yes"

- name: "Copy archivematica-mcp-client source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/lib/"
      dest: "/usr/lib/archivematica/MCPClient"

# For 1.6+ the location of archivematicaClientModules file is moved from
# src/MCPClient/etc/ to src/MCPClient/lib
# check if file is in etc/, if not there assume it is in lib/

- name: "check if archivematicaClientModules is in src/MCPClient/etc/"
  stat:
    path: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/etc/archivematicaClientModules"
  register: "p"

- name: "set fact for MCP clientConfig.conf"
  set_fact:
    archivematica_src_clientmodules: "/etc/archivematica/MCPClient/archivematicaClientModules"
  when: "p.stat.exists is defined and p.stat.exists"

- name: "set fact for MCP clientConfig.conf"
  set_fact:
    archivematica_src_clientmodules: "/usr/lib/archivematica/MCPClient/archivematicaClientModules"
  when: "p.stat.exists is defined and not p.stat.exists"

- name: "copy archivematicaClientModules to /etc/archivematica/MCPClient/ if required"
  command: "cp {{ archivematica_src_dir }}/archivematica/src/MCPClient/etc/archivematicaClientModules /etc/archivematica/MCPClient/"
  when: "p.stat.exists is defined and p.stat.exists"

- name: "Template MCPClient /etc config"
  template:
    src: "etc_archivematica_MCPClient_clientConfig.conf.j2"
    dest: "/etc/archivematica/MCPClient/clientConfig.conf"
    backup: "yes"

- name: "Template archivematica-mcp-server init service file"
  template:
    src: "etc_init_archivematica-mcp-server.conf.j2"
    dest: "/etc/init/archivematica-mcp-server.conf"
    backup: "yes"

- name: "Template archivematica-mcp-client init service file"
  template:
    src: "etc_init_archivematica-mcp-client.conf.j2"
    dest: "/etc/init/archivematica-mcp-client.conf"
    backup: "yes"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"
