---

###########################################################
#   1. OS dependencies (debian packages)
###########################################################

- name: "Add multiverse repositories"
  become: "yes"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"

# TODO: make this agree with tasks/old-main.yml
- name: "Install OLD package dependencies"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items: "{{ old_src_pkgdeps }}"


###########################################################
#   2. python dependencies (pip packages)
###########################################################

- name: "Install OLD pip dependencies"
  pip:
    requirements: "{{ old_src_dir }}/old/requirements.txt"
    state: "latest"
