---

###########################################################
#   5. Database reset (when flag enabled)
###########################################################

- name: "Drop OLD MySQL database"
  mysql_db:
    name: "{{ old_src_db_name }}"
    state: "absent"
  when: "old_src_reset_db|bool or old_src_reset_all|bool"


###########################################################
#   5. Database config
###########################################################

# Note that when we are using mysql_db and mysql_user we are assuming that the
# root user has a local ~/.my.cnf configuration file with the credentials in it
# for the MySQL user.

- name: "Create OLD MySQL database"
  mysql_db:
    name: "{{ old_src_db_name }}"
    state: "present"
    encoding: "utf8"
    collation: "utf8_unicode_ci"
  register: "createdb_result"

# TODO: need to change the mysql password for user old

- name: "Create MySQL user"
  mysql_user:
    name: "{{ old_src_db_user }}"
    password: "{{ old_src_db_password }}"
    priv: "{{ old_src_db_name }}.*:ALL"
    state: "present"

- name: "Create OLD database tables"
  shell: "/usr/share/python/old/bin/initialize_old_db development.ini"
  args:
    chdir: "{{ old_src_dir }}/old"

# TODO: OLD migrations?
