---

- name: "Run the equivalent of apt-get update"
  apt:
    update_cache: "yes"


- name: "Ensure pip is not installed from packages"
  package:
    name: "{{ item }}"
    state: "absent"
  with_items:
    - "python-pip"
    - "python2-pip"
    - "python3-pip"


- name: "Install necessary prerequisite packages"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items:
    - "python-pycurl"
    - "git"
    - "python-setuptools"
    - "python3-setuptools"
    - "python-virtualenv"

- name: "Download get-pip.py"
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: "/root/get-pip.py"

- name: "Install pip with get-pip.py"
  command: "python3 get-pip.py"
  args:
    chdir: "/root/"

- name: "Install virtualenv with pip"
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "virtualenv"

#- name: "install pip with easy_install"
#  easy_install:
#    name: "pip"
#    state: "latest"

- name: "Create user old"
  user:
    name: "old"
    uid: "333"
    system: "yes"
    groups: "audio"
    home: "/var/lib/old"

- name: "Add old user permissions in visudo file"
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^old ALL\\="
    line: "old ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape"
    validate: "/usr/sbin/visudo -cf %s"

- name: "Expand old_src_dir"
  set_fact:
    old_src_dir: "{{ old_src_dir|expanduser }}"

- name: "Create old_src_dir"
  file:
    state: "directory"
    path: "{{ old_src_dir }}"

# TODO: OLD sample data repo? Maybe a good idea...
# - name: "Checkout out old-sampledata repository"
