###########################################################
#   6- web server config - when using uwsgi with nginx
###########################################################

- name: "set nginx sites-available config file"
  template:
    src: "etc_nginx_sites_old.conf.j2"
    dest: "/etc/nginx/sites-available/old.conf"
    backup: "yes"
  tags: "oldsrc-websrv"

# TODO: using uwsgi in OLD deploys? ...

- name: "set uwsgi apps-available config file"
  template:
    src: "etc_uwsgi_apps.ini.j2"
    dest: "/etc/uwsgi/apps-available/old.ini"
    backup: "yes"
  tags: "oldsrc-websrv"

- name: "Remove Nginx default server"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-available/default.conf"
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-enabled/default.conf"
  tags: "oldsrc-websrv"

- name: "Set up Nginx server"
  file:
    src: "/etc/nginx/sites-available/old.conf"
    dest: "/etc/nginx/sites-enabled/old.conf"
    state: "link"
  tags: "oldsrc-websrv"

- name: "Set up uWSGI server"
  file:
    src: "/etc/uwsgi/apps-available/old.ini"
    dest: "/etc/uwsgi/apps-enabled/old.ini"
    state: "link"
  tags: "oldsrc-websrv"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "nginx"
    - "uwsgi"
  tags: "oldsrc-websrv"
